language: python
#notifications:
#  email:
#    - tfhartmann@gmail.com
python:
  - "2.7"
# command to install dependencies
install: 
  - "sudo wget -nv http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/vagrant_1.2.2_x86_64.deb"
  - "sudo dpkg -i vagrant_1.2.2_x86_64.deb"
  - pip install -r ./ci/requirements.txt
  - python setup.py develop
# command to run tests
script: 
  - flake8 .
  - nosetests -v
