language: python
notifications:
  email:
    - tfhartmann@gmail.com
python:
  - "2.7"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - python setup.py develop
# command to run tests
script: 
  - flake8 .
  - nosetests
